server:
  port: 8888

spring:
  application:
    name: careerorbit-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahulnanhore05/careerorbit-config.git
          username: rahulnanhore05
          password: ${CAREERORBIT_GIT_TOKEN}
          clone-on-start: true
          default-label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
